server:
  port: 8090
spring:
  profiles:
    active: dev
    include: secret
  datasource:
    url: jdbc:mysql://localhost:3306/surl_dev
    username: root
    password: lldj123414
    driver-class-name: com.mysql.cj.jdbc.Driver
custom:
  site:
    name: "My Site"

